### PR TITLE
Update readme to link to developer portal

### PR DESCRIPTION
**Pull request by libutcher**
This MR updates the readme to:
- Match the final edited text used in the developer portal
- Link out to the developer portal for usage examples beyond basic setup

### CODE REVIEW

**Comment by edif2008** [comment]
The README will also be used in the GitHub Marketplace, which is the place where folks may look for this action. Having the README page as suggested in this PR seems incomplete without some basic usage examples.

What I suggest is to provide the key snippets from the portal into this readme and then hint to the portal for more.
What do you think?

**Comment by libutcher** [comment]
> The README will also be used in the GitHub Marketplace, which is the place where folks may look for this action. Having the README page as suggested in this PR seems incomplete without some basic usage examples.
> 
> What I suggest is to provide the key snippets from the portal into this readme and then hint to the portal for more. What do you think?

Sure, I'll add those in then ping you for a second review!

**Comment by libutcher** [comment]
> The README will also be used in the GitHub Marketplace, which is the place where folks may look for this action. Having the README page as suggested in this PR seems incomplete without some basic usage examples.
> 
> What I suggest is to provide the key snippets from the portal into this readme and then hint to the portal for more. What do you think?

Done! Let me know if this looks better to you.

**Comment by edif2008** [comment]
Closing this as we will use a new template on the README.

**Pull request closed without merging**
